### ISSUE TITLE
Using plug-in in conjunction with ThreeWP Broadcast plug-in

### ISSUE THREAD

**Issue by marktoce** [voceconnect/multi-post-thumbnails#53]
Hello,

I've got a multi-site set-up that uses this plug-in https://wordpress.org/plugins/threewp-broadcast/ to push the content from the main site to the sub sites. Your plug-in is working great on the main site, but when I save and broadcast to the sub-site the "Secondary Image" field has no image associated with it.  

If it helps in trouble shooting, things are working as I hoped using the native "featured image" wordpress comes with. Thanks for any thoughts you may have.

mark

**Comment by chrisscott** [comment]
Hi Mark,

Make sure that the plugin is enabled on the sub-site and that the theme enables the MPT as well. IIRC, enabling a plugin on the main site doesn't enable it on other sites in the network. I think you'll need to go into your Network settings and enable the plugin for activation on other sites in the network first. 

Hope this helps.

**Comment by marktoce** [comment]
Hello, thanks for your thoughts! It is indeed enabled for all sites. I can see the "Secondary" image in the wordpress admin. The native Featured Image works fine when Broadcast out to the sub-sites... I'm wondering, what are the difference between the way the plug-in saves the image vs. the native Featured image.. maybe its getting lost somewhere. I'm also going to see if I can find something in the Broadacast plug-in, thanks for your help!

Mark

**Comment by chrisscott** [comment]
Ah, sorry, didn't catch that you were using the Broadcast plugin. The MPT is stored in the same manner as the featured image, via post meta. So, Broadcast would also need to be copying post meta. Even then, I think the issue is without Broadcast doing custom handling for it, the ID of the media set as the MPT would be off since it would be the ID of the media from the source blog. From a brief look at the source of that plugin, it doesn't look like it handles post meta at all so I'm not sure how even the standard featured image is getting set.
